version: '3'
services:
  db:
    image: postgres:9.6
    ports:
      - "5433:5432"
  web:
    build: .
    command: foreman start
    volumes:
      - .:/myapp
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://db:5432