
default: &default
  encoding: unicode
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password:
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: dawien_development

test:
  <<: *default
  database: dawien_test

production:
  <<: *default
  database: dawien_production
